export const SETACCOUNTINFORMATION = 'SETACCOUNTINFORMATION';
export const SETUSERINFORMATION = 'SETUSERINFORMATION';
export const SETPOST = 'SETPOST';
export const SETSTICKYTABLE = 'SETSTICKYTABLE';
export const ADDCOMMENT = 'ADDCOMMENT';
export const SETTOKEN = 'SETTOKEN';
export const ISLOADED = 'ISLOADED';
export const COMMENTCOUNTER = 'COMMENTCOUNTER';
export const SETNEWRATING = 'SETNEWRATING';
export const SETDEPARTAMENT = 'SETDEPARTAMENT';
export const GETTEACHERS = 'GETTEACHERS';

